logging:
  config: classpath:logback-spring-local.xml
  level:
    org.springframework.web.client.RestTemplate: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cryptotracker-db
    username: myuser
    password: mysecretpassword