logging:
  level:
    liquibase: DEBUG
    root: WARN
    org:
      postgresql.Driver: INFO
      hibernate:
        SQL: DEBUG
        stat: INFO
        type.descriptor.sql.BasicBinder: TRACE
      springframework:
        boot.autoconfigure: DEBUG
        jdbc:
          core:
            JdbcTemplate: DEBUG
            StatementCreatorUtils: TRACE
        # Log Oauth2
        security.oauth2.client: DEBUG
        # Log restTemplate
        web.client.RestTemplate: DEBUG
