name: Deploy-artifact-workflow

on:
  workflow_dispatch

jobs:
  deploy-artifact:
    name: Deploy-artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 18
          distribution: 'temurin'
          cache: 'maven'
      - name: Publish artifact on GitHub Packages
        run: mvn -B -e -X clean deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.USER_GITHUB_TOKEN }}
