name: Branch Others workflow

on:
  push:
  pull_request:
    branches-ignore:
      - develop
      - master

jobs:
  buildAndSonar:
    name: Build-app
    runs-on: ubuntu-latest
    steps:
      - name: build_sonar_ext
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          workflow: Build-app-workflow
          token: ${{ secrets.USER_GITHUB_TOKEN }}
          display-workflow-run-url: true
          display-workflow-run-url-timeout: 10m
          display-workflow-run-url-interval: 15s
          wait-for-completion-timeout: 10m
          wait-for-completion-interval: 15s
