name: Release workflow

on:
  workflow_dispatch:
    tags:
      - "crypto-tracker-[0-9]+.[0-9]+.[0-9]+"

jobs:
  buildAndSonar:
    name: Build-app
    runs-on: ubuntu-latest
    steps:
      - name: build_sonar_ext
        uses: aurelien-baudet/workflow-dispatch@v2.1.1
        with:
          workflow: Build-app-workflow
          token: ${{ secrets.USER_GITHUB_TOKEN }}
          display-workflow-run-url: true
          display-workflow-run-url-timeout: 10m
          display-workflow-run-url-interval: 15s
          wait-for-completion-timeout: 10m
          wait-for-completion-interval: 15s

  build-docker-version:
    name: Build-docker-version
    runs-on: ubuntu-latest
    needs: [ buildAndSonar ]
    steps:
      - name: build-docker-latest_ext
        uses: aurelien-baudet/workflow-dispatch@v2.1.1
        with:
          workflow: Build-docker-workflow
          token: ${{ secrets.USER_GITHUB_TOKEN }}
          display-workflow-run-url: true
          display-workflow-run-url-timeout: 10m
          display-workflow-run-url-interval: 15s
          wait-for-completion-timeout: 10m
          wait-for-completion-interval: 15s
          inputs: '{ "version": "true" }'